root = Tk() 
root.configure(background='light green') 
root.title("registration form") 
root.geometry("500x300") 

heading = Label(root, text="Form", bg="light green") 
name = Label(root, text="Name", bg="light green") 
course = Label(root, text="Course", bg="light green") 
sem = Label(root, text="Semester", bg="light green") 
form_no = Label(root, text="Form No.", bg="light green") 
contact_no = Label(root, text="Contact No.", bg="light green") 
email_id = Label(root, text="Email id", bg="light green") 
address = Label(root, text="Address", bg="light green") 

heading.grid(row=0, column=1) 
name.grid(row=1, column=0) 
course.grid(row=2, column=0) 
sem.grid(row=3, column=0) 
form_no.grid(row=4, column=0) 
contact_no.grid(row=5, column=0) 
email_id.grid(row=6, column=0) 
address.grid(row=7, column=0) 

name_field = Entry(root) 
course_field = Entry(root) 
sem_field = Entry(root) 
form_no_field = Entry(root) 
contact_no_field = Entry(root) 
email_id_field = Entry(root) 
address_field = Entry(root) 

name_field.grid(row=1, column=1, ipadx="100") 
course_field.grid(row=2, column=1, ipadx="100") 
sem_field.grid(row=3, column=1, ipadx="100") 
form_no_field.grid(row=4, column=1, ipadx="100") 
contact_no_field.grid(row=5, column=1, ipadx="100") 
email_id_field.grid(row=6, column=1, ipadx="100") 
address_field.grid(row=7, column=1, ipadx="100") 

submit = Button(root, text="Submit", fg="Black", 
                        bg="Red") 
submit.grid(row=8, column=1) 

root.mainloop() 